//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace cab_booking1.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CBEntities object using the connection string found in the 'CBEntities' section of the application configuration file.
        /// </summary>
        public CBEntities() : base("name=CBEntities", "CBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CBEntities object.
        /// </summary>
        public CBEntities(string connectionString) : base(connectionString, "CBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CBEntities object.
        /// </summary>
        public CBEntities(EntityConnection connection) : base(connection, "CBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Location> Locations
        {
            get
            {
                if ((_Locations == null))
                {
                    _Locations = base.CreateObjectSet<Location>("Locations");
                }
                return _Locations;
            }
        }
        private ObjectSet<Location> _Locations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TIMING> TIMINGS
        {
            get
            {
                if ((_TIMINGS == null))
                {
                    _TIMINGS = base.CreateObjectSet<TIMING>("TIMINGS");
                }
                return _TIMINGS;
            }
        }
        private ObjectSet<TIMING> _TIMINGS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BOOKING> BOOKINGs
        {
            get
            {
                if ((_BOOKINGs == null))
                {
                    _BOOKINGs = base.CreateObjectSet<BOOKING>("BOOKINGs");
                }
                return _BOOKINGs;
            }
        }
        private ObjectSet<BOOKING> _BOOKINGs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DRIVER> DRIVERs
        {
            get
            {
                if ((_DRIVERs == null))
                {
                    _DRIVERs = base.CreateObjectSet<DRIVER>("DRIVERs");
                }
                return _DRIVERs;
            }
        }
        private ObjectSet<DRIVER> _DRIVERs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EMPLOYEE> EMPLOYEEs
        {
            get
            {
                if ((_EMPLOYEEs == null))
                {
                    _EMPLOYEEs = base.CreateObjectSet<EMPLOYEE>("EMPLOYEEs");
                }
                return _EMPLOYEEs;
            }
        }
        private ObjectSet<EMPLOYEE> _EMPLOYEEs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VEHICLE_DETAILS> VEHICLE_DETAILS
        {
            get
            {
                if ((_VEHICLE_DETAILS == null))
                {
                    _VEHICLE_DETAILS = base.CreateObjectSet<VEHICLE_DETAILS>("VEHICLE_DETAILS");
                }
                return _VEHICLE_DETAILS;
            }
        }
        private ObjectSet<VEHICLE_DETAILS> _VEHICLE_DETAILS;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Locations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocations(Location location)
        {
            base.AddObject("Locations", location);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TIMINGS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTIMINGS(TIMING tIMING)
        {
            base.AddObject("TIMINGS", tIMING);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BOOKINGs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBOOKINGs(BOOKING bOOKING)
        {
            base.AddObject("BOOKINGs", bOOKING);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DRIVERs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDRIVERs(DRIVER dRIVER)
        {
            base.AddObject("DRIVERs", dRIVER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EMPLOYEEs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEMPLOYEEs(EMPLOYEE eMPLOYEE)
        {
            base.AddObject("EMPLOYEEs", eMPLOYEE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VEHICLE_DETAILS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVEHICLE_DETAILS(VEHICLE_DETAILS vEHICLE_DETAILS)
        {
            base.AddObject("VEHICLE_DETAILS", vEHICLE_DETAILS);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="BOOKING")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BOOKING : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BOOKING object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static BOOKING CreateBOOKING(global::System.Int32 id)
        {
            BOOKING bOOKING = new BOOKING();
            bOOKING.ID = id;
          
            return bOOKING;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EMP_ID
        {
            get
            {
                return _EMP_ID;
            }
            set
            {
                OnEMP_IDChanging(value);
                ReportPropertyChanging("EMP_ID");
                _EMP_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EMP_ID");
                OnEMP_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _EMP_ID;
        partial void OnEMP_IDChanging(Nullable<global::System.Int32> value);
        partial void OnEMP_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LOC_ID
        {
            get
            {
                return _LOC_ID;
            }
            set
            {
                OnLOC_IDChanging(value);
                ReportPropertyChanging("LOC_ID");
                _LOC_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOC_ID");
                OnLOC_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _LOC_ID;
        partial void OnLOC_IDChanging(Nullable<global::System.Int32> value);
        partial void OnLOC_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TIMING
        {
            get
            {
                return _TIMING;
            }
            set
            {
                OnTIMINGChanging(value);
                ReportPropertyChanging("TIMING");
                _TIMING = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIMING");
                OnTIMINGChanged();
            }
        }
        private Nullable<global::System.DateTime> _TIMING;
        partial void OnTIMINGChanging(Nullable<global::System.DateTime> value);
        partial void OnTIMINGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                OnTYPEChanging(value);
                ReportPropertyChanging("TYPE");
                _TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TYPE");
                OnTYPEChanged();
            }
        }
        private global::System.String _TYPE;
        partial void OnTYPEChanging(global::System.String value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CAB_ID
        {
            get
            {
                return _CAB_ID;
            }
            set
            {
                OnCAB_IDChanging(value);
                ReportPropertyChanging("CAB_ID");
                _CAB_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CAB_ID");
                OnCAB_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _CAB_ID;
        partial void OnCAB_IDChanging(Nullable<global::System.Int32> value);
        partial void OnCAB_IDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="DRIVER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DRIVER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DRIVER object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static DRIVER CreateDRIVER(global::System.Int32 id)
        {
            DRIVER dRIVER = new DRIVER();
            dRIVER.ID = id;
            return dRIVER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONTACT_NUMBER
        {
            get
            {
                return _CONTACT_NUMBER;
            }
            set
            {
                OnCONTACT_NUMBERChanging(value);
                ReportPropertyChanging("CONTACT_NUMBER");
                _CONTACT_NUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CONTACT_NUMBER");
                OnCONTACT_NUMBERChanged();
            }
        }
        private global::System.String _CONTACT_NUMBER;
        partial void OnCONTACT_NUMBERChanging(global::System.String value);
        partial void OnCONTACT_NUMBERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LICENSE_NUMBER
        {
            get
            {
                return _LICENSE_NUMBER;
            }
            set
            {
                OnLICENSE_NUMBERChanging(value);
                ReportPropertyChanging("LICENSE_NUMBER");
                _LICENSE_NUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LICENSE_NUMBER");
                OnLICENSE_NUMBERChanged();
            }
        }
        private global::System.String _LICENSE_NUMBER;
        partial void OnLICENSE_NUMBERChanging(global::System.String value);
        partial void OnLICENSE_NUMBERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADDRESS
        {
            get
            {
                return _ADDRESS;
            }
            set
            {
                OnADDRESSChanging(value);
                ReportPropertyChanging("ADDRESS");
                _ADDRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADDRESS");
                OnADDRESSChanged();
            }
        }
        private global::System.String _ADDRESS;
        partial void OnADDRESSChanging(global::System.String value);
        partial void OnADDRESSChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="EMPLOYEE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EMPLOYEE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EMPLOYEE object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static EMPLOYEE CreateEMPLOYEE(global::System.Int32 id)
        {
            EMPLOYEE eMPLOYEE = new EMPLOYEE();
            eMPLOYEE.ID = id;
            return eMPLOYEE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADDRESS
        {
            get
            {
                return _ADDRESS;
            }
            set
            {
                OnADDRESSChanging(value);
                ReportPropertyChanging("ADDRESS");
                _ADDRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADDRESS");
                OnADDRESSChanged();
            }
        }
        private global::System.String _ADDRESS;
        partial void OnADDRESSChanging(global::System.String value);
        partial void OnADDRESSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESIGNATION
        {
            get
            {
                return _DESIGNATION;
            }
            set
            {
                OnDESIGNATIONChanging(value);
                ReportPropertyChanging("DESIGNATION");
                _DESIGNATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESIGNATION");
                OnDESIGNATIONChanged();
            }
        }
        private global::System.String _DESIGNATION;
        partial void OnDESIGNATIONChanging(global::System.String value);
        partial void OnDESIGNATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OFFICE_LOCATION
        {
            get
            {
                return _OFFICE_LOCATION;
            }
            set
            {
                OnOFFICE_LOCATIONChanging(value);
                ReportPropertyChanging("OFFICE_LOCATION");
                _OFFICE_LOCATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OFFICE_LOCATION");
                OnOFFICE_LOCATIONChanged();
            }
        }
        private global::System.String _OFFICE_LOCATION;
        partial void OnOFFICE_LOCATIONChanging(global::System.String value);
        partial void OnOFFICE_LOCATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SHIFT_ID
        {
            get
            {
                return _SHIFT_ID;
            }
            set
            {
                OnSHIFT_IDChanging(value);
                ReportPropertyChanging("SHIFT_ID");
                _SHIFT_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SHIFT_ID");
                OnSHIFT_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _SHIFT_ID;
        partial void OnSHIFT_IDChanging(Nullable<global::System.Int32> value);
        partial void OnSHIFT_IDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Location : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Location object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Location CreateLocation(global::System.Int32 id)
        {
            Location location = new Location();
            location.ID = id;
            return location;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AREA
        {
            get
            {
                return _AREA;
            }
            set
            {
                OnAREAChanging(value);
                ReportPropertyChanging("AREA");
                _AREA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AREA");
                OnAREAChanged();
            }
        }
        private global::System.String _AREA;
        partial void OnAREAChanging(global::System.String value);
        partial void OnAREAChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="TIMING")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TIMING : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TIMING object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static TIMING CreateTIMING(global::System.Int32 id)
        {
            TIMING tIMING = new TIMING();
            tIMING.ID = id;
            return tIMING;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TIMING1
        {
            get
            {
                return _TIMING1;
            }
            set
            {
                OnTIMING1Changing(value);
                ReportPropertyChanging("TIMING1");
                _TIMING1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TIMING1");
                OnTIMING1Changed();
            }
        }
        private global::System.String _TIMING1;
        partial void OnTIMING1Changing(global::System.String value);
        partial void OnTIMING1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                OnTYPEChanging(value);
                ReportPropertyChanging("TYPE");
                _TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TYPE");
                OnTYPEChanged();
            }
        }
        private global::System.String _TYPE;
        partial void OnTYPEChanging(global::System.String value);
        partial void OnTYPEChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VEHICLE_DETAILS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VEHICLE_DETAILS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VEHICLE_DETAILS object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static VEHICLE_DETAILS CreateVEHICLE_DETAILS(global::System.Int32 id)
        {
            VEHICLE_DETAILS vEHICLE_DETAILS = new VEHICLE_DETAILS();
            vEHICLE_DETAILS.ID = id;
            return vEHICLE_DETAILS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CAB_NUMBER
        {
            get
            {
                return _CAB_NUMBER;
            }
            set
            {
                OnCAB_NUMBERChanging(value);
                ReportPropertyChanging("CAB_NUMBER");
                _CAB_NUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CAB_NUMBER");
                OnCAB_NUMBERChanged();
            }
        }
        private global::System.String _CAB_NUMBER;
        partial void OnCAB_NUMBERChanging(global::System.String value);
        partial void OnCAB_NUMBERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REGISTRATION_NUMBER
        {
            get
            {
                return _REGISTRATION_NUMBER;
            }
            set
            {
                OnREGISTRATION_NUMBERChanging(value);
                ReportPropertyChanging("REGISTRATION_NUMBER");
                _REGISTRATION_NUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REGISTRATION_NUMBER");
                OnREGISTRATION_NUMBERChanged();
            }
        }
        private global::System.String _REGISTRATION_NUMBER;
        partial void OnREGISTRATION_NUMBERChanging(global::System.String value);
        partial void OnREGISTRATION_NUMBERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CAPACITY
        {
            get
            {
                return _CAPACITY;
            }
            set
            {
                OnCAPACITYChanging(value);
                ReportPropertyChanging("CAPACITY");
                _CAPACITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CAPACITY");
                OnCAPACITYChanged();
            }
        }
        private Nullable<global::System.Int32> _CAPACITY;
        partial void OnCAPACITYChanging(Nullable<global::System.Int32> value);
        partial void OnCAPACITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                OnTYPEChanging(value);
                ReportPropertyChanging("TYPE");
                _TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TYPE");
                OnTYPEChanged();
            }
        }
        private global::System.String _TYPE;
        partial void OnTYPEChanging(global::System.String value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OWNER_NAME
        {
            get
            {
                return _OWNER_NAME;
            }
            set
            {
                OnOWNER_NAMEChanging(value);
                ReportPropertyChanging("OWNER_NAME");
                _OWNER_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OWNER_NAME");
                OnOWNER_NAMEChanged();
            }
        }
        private global::System.String _OWNER_NAME;
        partial void OnOWNER_NAMEChanging(global::System.String value);
        partial void OnOWNER_NAMEChanged();

        #endregion

    
    }

    #endregion

    
}
